version: '3'

services:
  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    ports:
      - "8085:80"
      - "8125:8125/udp"
      - "8126:8126"

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - graphite

  backend:
    build: .
    container_name: backend
    ports:
      - "8081:8081"
    depends_on:
      - graphite
    restart: always
